input {
  tcp {
    port => 5000
    codec => json_lines
    add_field => { "service" => "fastify-backend" }
  }
}

filter {
  if [msg] == "🚀 Server is running" {
    mutate { add_tag => ["startup"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "transcendence-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "user1234567"
  }
  # stdout { codec => rubydebug }
}